# Generated by Django 5.0.6 on 2024-06-08 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_course_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_time', models.CharField(max_length=100)),
                ('course_day', models.CharField(max_length=123)),
                ('course_duration', models.CharField(max_length=123)),
                ('is_teens', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.PositiveIntegerField(choices=[(1, 'recruitment is open'), (2, 'recruitment is closed'), (3, 'recruitment is soon')], default=3)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
            options={
                'verbose_name': 'Course ',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
